fuzz testing
Use via:
```
cargo +nightly install cargo-fuzz
cargo +nightly fuzz run parse_session
```

This finds eg panics due to multiplicative overflow.

```
thread '<unnamed>' panicked at 'attempt to multiply with overflow', /home/slamb/git/crates/sdp/src/session_description.rs:1345:17

...

Output of `std::fmt::Debug`:

        [118, 61, 48, 10, 111, 61, 48, 11, 49, 11, 48, 9, 73, 78, 9, 73, 80, 54, 13, 1, 61, 0, 61, 47, 10,
 115, 61, 53, 9, 9, 48, 26, 10, 116, 61, 48, 11, 50, 55, 10, 114, 61, 48, 11, 50, 11, 48, 48, 48, 48, 48,
51, 55, 49, 52, 50, 50, 54, 53, 50, 53, 57, 54, 54, 51, 49, 55, 57, 53, 109, 9, 48, 11, 9, 126, 119, 115, 58, 0, 0]
```